language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  # tagging
  - docker tag udagram-api-feed delors/udagram-api-feed:v1
  - docker tag udagram-api-user delors/udagram-api-user:v1
  - docker tag udagram-frontend:local delors/udagram-frontend:v1
  - docker tag reverseproxy delors/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push delors/udagram-api-feed:v1
  - docker push delors/udagram-api-user:v1
  - docker push delors/udagram-frontend:v1
  - docker push delors/reverseproxy:v1